2023-05-17 17:11:59,461-ERROR-logger.py-[ line:62 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
2023-05-17 17:11:59,504-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:1 不执行，跳过!!!
2023-05-17 17:12:00,124-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:3 不执行，跳过!!!
2023-05-17 17:12:00,962-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:None 不执行，跳过!!!
2023-05-17 17:12:00,963-ERROR-logger.py-[ line:62 ] - 日志信息:所有用例执行完毕
2023-05-17 17:12:52,979-ERROR-logger.py-[ line:62 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
2023-05-17 17:12:52,984-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:1 不执行，跳过!!!
2023-05-17 17:12:53,448-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:3 不执行，跳过!!!
2023-05-17 17:12:54,262-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:None 不执行，跳过!!!
2023-05-17 17:12:54,263-ERROR-logger.py-[ line:62 ] - 日志信息:所有用例执行完毕
2023-05-17 17:14:33,655-ERROR-logger.py-[ line:62 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
2023-05-17 17:14:33,659-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:1 不执行，跳过!!!
2023-05-17 17:14:34,215-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:3 不执行，跳过!!!
2023-05-17 17:14:35,157-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:None 不执行，跳过!!!
2023-05-17 17:14:35,158-ERROR-logger.py-[ line:62 ] - 日志信息:所有用例执行完毕
2023-05-17 17:17:15,935-ERROR-logger.py-[ line:62 ] - 日志信息:读取excel中初始化数据异常: [Errno 13] Permission denied: 'D:\\apk_api\\api-test-project\\data\\test_cases\\test_api.xlsx'
2023-05-17 17:19:23,001-ERROR-logger.py-[ line:62 ] - 日志信息:读取excel中初始化数据异常: [Errno 13] Permission denied: 'D:\\apk_api\\api-test-project\\data\\test_cases\\test_api.xlsx'
2023-05-17 17:20:56,961-ERROR-logger.py-[ line:62 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
2023-05-17 17:20:56,965-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:1 不执行，跳过!!!
2023-05-17 17:20:57,456-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:3 不执行，跳过!!!
2023-05-17 17:20:58,254-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:None 不执行，跳过!!!
2023-05-17 17:20:58,255-ERROR-logger.py-[ line:62 ] - 日志信息:所有用例执行完毕
2023-05-17 17:21:07,759-ERROR-logger.py-[ line:62 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '127.0.0.1' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
2023-05-17 17:21:07,763-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:1 不执行，跳过!!!
2023-05-17 17:21:08,297-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:3 不执行，跳过!!!
2023-05-17 17:21:09,085-ERROR-logger.py-[ line:62 ] - 日志信息:测试用例:None 不执行，跳过!!!
2023-05-17 17:21:09,086-ERROR-logger.py-[ line:62 ] - 日志信息:所有用例执行完毕
