2023-03-28 23:05:01,363-ERROR-logger.py-[ line:63 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '10.8.203.25' (timed out)")
2023-03-28 23:05:01,475-ERROR-logger.py-[ line:63 ] - 日志信息:post 请求异常:HTTPSConnectionPool(host='bimdc.bzlrobot.com', port=443): Max retries exceeded with url: /bsp/test/user/ugs/auth/loginByNotBip (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
URL:https://bimdc.bzlrobot.com/bsp/test/user/ugs/auth/loginByNotBip
参数:{'account': '18127813600', 'password': None}
2023-03-28 23:05:01,479-ERROR-logger.py-[ line:63 ] - 日志信息:登录失败: 'NoneType' object has no attribute 'json'
2023-03-28 23:05:01,599-ERROR-logger.py-[ line:63 ] - 日志信息:None: test_api() missing 1 required positional argument: 'item'
2023-03-28 23:05:56,582-ERROR-logger.py-[ line:63 ] - 日志信息:数据库链接失败: (2003, "Can't connect to MySQL server on '10.8.203.25' (timed out)")
2023-03-28 23:05:56,691-ERROR-logger.py-[ line:63 ] - 日志信息:post 请求异常:HTTPSConnectionPool(host='bimdc.bzlrobot.com', port=443): Max retries exceeded with url: /bsp/test/user/ugs/auth/loginByNotBip (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
URL:https://bimdc.bzlrobot.com/bsp/test/user/ugs/auth/loginByNotBip
参数:{'account': '18127813600', 'password': None}
2023-03-28 23:05:56,695-ERROR-logger.py-[ line:63 ] - 日志信息:登录失败: 'NoneType' object has no attribute 'json'
